<a href="https://colab.research.google.com/github/Nihal108-bi/Nihal-AI-ML-Practice-Hub/blob/Pytorch_full_Practice_with_project/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

# Train test split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

# Scaling

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
X_train,X_test

(array([[-1.51908854, -1.06593651, -1.39468435, ..., -1.01260399,
         -1.08783509,  1.48447558],
        [-1.25828969, -0.52037323, -1.23644548, ..., -0.92697206,
         -0.60798789,  0.08052495],
        [-0.76749502,  0.40360202, -0.75405151, ..., -0.80305577,
         -0.21413481,  0.30721681],
        ...,
        [-1.33837753, -1.5766766 , -1.32857377, ..., -0.78742951,
         -0.75073813, -0.33083496],
        [-0.28051406, -0.85235429, -0.18251488, ...,  1.3428992 ,
          0.44801992,  3.38442564],
        [-0.36852267, -1.43274076, -0.43501465, ..., -1.13698906,
         -1.89789972, -0.59955064]]),
 array([[-1.5827481 , -1.11004588, -1.58107354, ..., -1.76047703,
         -0.50651483, -0.2864436 ],
        [-0.85257001,  0.50575004, -0.87603619, ..., -1.08761006,
          0.15392003, -0.71556005],
        [-0.77336226, -0.89182057, -0.7860405 , ..., -0.43599481,
         -0.3620447 , -0.92745479],
        ...,
        [ 2.08105025,  0.88416202,  1.94965795, ...,  

In [ ]:
y_train

71     B
110    B
80     B
132    M
371    B
      ..
126    M
299    B
21     B
105    M
179    B
Name: diagnosis, Length: 455, dtype: object

# LabelEncoding

In [ ]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [ ]:
y_train,y_test

(array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
        1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
        1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
        0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 

# Numpy arrays to pytorch tensors

In [ ]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
X_train_tensor

tensor([[-1.5191, -1.0659, -1.3947,  ..., -1.0126, -1.0878,  1.4845],
        [-1.2583, -0.5204, -1.2364,  ..., -0.9270, -0.6080,  0.0805],
        [-0.7675,  0.4036, -0.7541,  ..., -0.8031, -0.2141,  0.3072],
        ...,
        [-1.3384, -1.5767, -1.3286,  ..., -0.7874, -0.7507, -0.3308],
        [-0.2805, -0.8524, -0.1825,  ...,  1.3429,  0.4480,  3.3844],
        [-0.3685, -1.4327, -0.4350,  ..., -1.1370, -1.8979, -0.5996]],
       dtype=torch.float64)

In [ ]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [ ]:
class MySimpleNN():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.matmul(X,self.weights) + self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss



# Important Parameters

In [ ]:
learning_rate=0.1
epochs=50

# Training Pipeline

In [ ]:
#create model
model=MySimpleNN(X_train_tensor)
model.weights

tensor([[0.8329],
        [0.4241],
        [0.5401],
        [0.6231],
        [0.7400],
        [0.5061],
        [0.6675],
        [0.9597],
        [0.0928],
        [0.9170],
        [0.0871],
        [0.7107],
        [0.1785],
        [0.9384],
        [0.4593],
        [0.8949],
        [0.8530],
        [0.4676],
        [0.4643],
        [0.4180],
        [0.4725],
        [0.1752],
        [0.0176],
        [0.4117],
        [0.3882],
        [0.9586],
        [0.9318],
        [0.3296],
        [0.1035],
        [0.7495]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [ ]:
#define loop
for epoch in range(epochs):

  #forward pass
  y_pred=model.forward(X_train_tensor)

  #loss calculate
  loss=model.loss_function(y_pred,y_train_tensor)

  #backward pass
  loss.backward()

  #parameters update
  with torch.no_grad():
    model.weights -=learning_rate*model.weights.grad
    model.bias -=learning_rate*model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss
  print(f"epoch:{epoch+1},loss:{loss.item()}")


epoch:1,loss:0.8728825515378354
epoch:2,loss:0.8418042947161501
epoch:3,loss:0.8168838138502706
epoch:4,loss:0.7967208470920687
epoch:5,loss:0.7802240972229473
epoch:6,loss:0.7665757212328658
epoch:7,loss:0.7551746757661747
epoch:8,loss:0.7455783746178176
epoch:9,loss:0.7374544840671342
epoch:10,loss:0.7305461286514547
epoch:11,loss:0.7246487736618007
epoch:12,loss:0.7195955217266213
epoch:13,loss:0.7152478586320249
epoch:14,loss:0.7114897205042761
epoch:15,loss:0.7082235214233312
epoch:16,loss:0.7053673138691642
epoch:17,loss:0.7028525875452314
epoch:18,loss:0.7006224209216947
epoch:19,loss:0.6986298370104974
epoch:20,loss:0.6968363035100297
epoch:21,loss:0.6952103671405402
epoch:22,loss:0.6937264317273948
epoch:23,loss:0.6923636904148498
epoch:24,loss:0.69110521465454
epoch:25,loss:0.6899371934689624
epoch:26,loss:0.6888483095112797
epoch:27,loss:0.6878292345942237
epoch:28,loss:0.6868722262451248
epoch:29,loss:0.6859708076090472
epoch:30,loss:0.6851195148434285
epoch:31,loss:0.68431

In [ ]:
model.weights

tensor([[ 0.4282],
        [ 0.0679],
        [ 0.0948],
        [ 0.1883],
        [ 0.1495],
        [-0.3086],
        [-0.1516],
        [ 0.2429],
        [-0.1788],
        [ 0.3169],
        [-0.3610],
        [ 0.2344],
        [-0.2955],
        [ 0.5251],
        [ 0.0097],
        [ 0.0718],
        [ 0.1809],
        [-0.1950],
        [ 0.1377],
        [-0.2465],
        [ 0.0719],
        [-0.1877],
        [-0.4210],
        [-0.0054],
        [-0.1002],
        [ 0.2524],
        [ 0.1933],
        [-0.2792],
        [-0.0714],
        [ 0.0691]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.4490], dtype=torch.float64, requires_grad=True)

# Evaluation

In [ ]:
#model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred >0.5).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5609418153762817
